id: P006648
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:12:43.896717
source_metadata:
  id: bdr:W2CZ6593
  title: ཨོ་རྒྱན་ཀུན་བཟང་ཆོས་འཁོར་གླིང་གི་འདོན་ཆ་
  author: ''
  volumes:
    27434f141fee436c8ff3d0ee0ef29122:
      image_group_id: I1KG1399
      title: ''
      volume_number: 1
      total_pages: 682
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
