id: P006648
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ6593
  title: ཨོ་རྒྱན་ཀུན་བཟང་ཆོས་འཁོར་གླིང་གི་འདོན་ཆ་
  author: ''
  volumes:
    27434f141fee436c8ff3d0ee0ef29122:
      image_group_id: I1KG1399
      title: ''
      volume_number: 1
      total_pages: 682
